### ISSUE TITLE
ERROR:  output_avro_change: row conversion failed: Field index 1 out of range

### ISSUE THREAD

**Issue by zcox** [confluentinc/bottledwater-pg#32] opened 2015-12-02 21:08 UTC
I'm testing out bottled-water with a [really simple application](https://github.com/zcox/data-replication-example) based on two Postgres tables: users and tweets. I consume the Twitter Streaming API and insert users and tweets into the tables, then have Kafka consumers writing data to various data stores.

Shortly after starting the application, usually between 10 seconds and 1 minute, bottled-water will crash with something like the following output:

```
bottledwater_1 | INFO:  Row conversion failed: relation oid=16392 name=users ns=public relkind=r
bottledwater_1 |     0. attrelid = 16392, attname = id, atttypid = 20, attlen = 8, attnum = 1, attndims = 0, atttypmod = -1, attnotnull = 1, atthasdef = 1, attisdropped = 0, attcollation = 0
bottledwater_1 |     1. attrelid = 16392, attname = username, atttypid = 1043, attlen = -1, attnum = 2, attndims = 0, atttypmod = 54, attnotnull = 1, atthasdef = 0, attisdropped = 0, attcollation = 100
bottledwater_1 |     2. attrelid = 16392, attname = name, atttypid = 25, attlen = -1, attnum = 3, attndims = 0, atttypmod = -1, attnotnull = 0, atthasdef = 0, attisdropped = 0, attcollation = 100
bottledwater_1 |     3. attrelid = 16392, attname = description, atttypid = 25, attlen = -1, attnum = 4, attndims = 0, atttypmod = -1, attnotnull = 0, atthasdef = 0, attisdropped = 0, attcollation = 100
bottledwater_1 |     4. attrelid = 16392, attname = image_url, atttypid = 25, attlen = -1, attnum = 5, attndims = 0, atttypmod = -1, attnotnull = 0, atthasdef = 0, attisdropped = 0, attcollation = 100
bottledwater_1 | replica identity index: oid=16399 name=users_pkey ns=public
bottledwater_1 |     0. attrelid = 16399, attname = id, atttypid = 20, attlen = 8, attnum = 1, attndims = 0, atttypmod = -1, attnotnull = 0, atthasdef = 0, attisdropped = 0, attcollation = 0
bottledwater_1 | CONTEXT:  slot "bottledwater", output plugin "bottledwater", in the change callback, associated LSN 0/17DB2D0
bottledwater_1 | /usr/local/bin/bottledwater: Replication stream was unexpectedly terminated: ERROR:  output_avro_change: row conversion failed: Field index 1 out of range
bottledwater_1 | CONTEXT:  slot "bottledwater", output plugin "bottledwater", in the change callback, associated LSN 0/17DB2D0
```

Here's another example, but for the tweets table:

```
bottledwater_1 | INFO:  Row conversion failed: relation oid=16405 name=tweets ns=public relkind=r
bottledwater_1 | 	   0. attrelid = 16405, attname = id, atttypid = 20, attlen = 8, attnum = 1, attndims = 0, atttypmod = -1, attnotnull = 1, atthasdef = 1, attisdropped = 0, attcollation = 0
bottledwater_1 | 	   1. attrelid = 16405, attname = content, atttypid = 25, attlen = -1, attnum = 2, attndims = 0, atttypmod = -1, attnotnull = 0, atthasdef = 0, attisdropped = 0, attcollation = 100
bottledwater_1 | 	   2. attrelid = 16405, attname = created_at, atttypid = 1114, attlen = 8, attnum = 3, attndims = 0, atttypmod = -1, attnotnull = 0, atthasdef = 0, attisdropped = 0, attcollation = 0
bottledwater_1 | 	   3. attrelid = 16405, attname = latitude, atttypid = 701, attlen = 8, attnum = 4, attndims = 0, atttypmod = -1, attnotnull = 0, atthasdef = 0, attisdropped = 0, attcollation = 0
bottledwater_1 | 	   4. attrelid = 16405, attname = longitude, atttypid = 701, attlen = 8, attnum = 5, attndims = 0, atttypmod = -1, attnotnull = 0, atthasdef = 0, attisdropped = 0, attcollation = 0
bottledwater_1 | 	   5. attrelid = 16405, attname = user_id, atttypid = 20, attlen = 8, attnum = 6, attndims = 0, atttypmod = -1, attnotnull = 1, atthasdef = 0, attisdropped = 0, attcollation = 0
bottledwater_1 | replica identity index: oid=16412 name=tweets_pkey ns=public
bottledwater_1 | 	   0. attrelid = 16412, attname = id, atttypid = 20, attlen = 8, attnum = 1, attndims = 0, atttypmod = -1, attnotnull = 0, atthasdef = 0, attisdropped = 0, attcollation = 0
bottledwater_1 | CONTEXT:  slot "bottledwater", output plugin "bottledwater", in the change callback, associated LSN 0/17A9BF0
bottledwater_1 | /usr/local/bin/bottledwater: Replication stream was unexpectedly terminated: ERROR:  output_avro_change: row conversion failed: Field index 1 out of range
bottledwater_1 | CONTEXT:  slot "bottledwater", output plugin "bottledwater", in the change callback, associated LSN 0/17A9BF0
```

In both cases, the error message is the same: `Field index 1 out of range`. The only line in avro-c that logs that error message is in this function:

http://svn.apache.org/viewvc/avro/tags/release-1.7.7/lang/c/src/generic.c?view=markup#l2948

```c
static int
avro_generic_record_get_by_index(const avro_value_iface_t *viface,
                                 const void *vself, size_t index,
                                 avro_value_t *child, const char **name)
{
        const avro_generic_record_value_iface_t  *iface =
            container_of(viface, avro_generic_record_value_iface_t, parent);
        const avro_generic_record_t  *self = (const avro_generic_record_t *) vself;
        if (index >= iface->field_count) {
                avro_set_error("Field index %" PRIsz " out of range", index);
                return EINVAL;
        }
        child->iface = &iface->field_ifaces[index]->parent;
        child->self = avro_generic_record_field(iface, self, index);

        /*
         * Grab the field name from the schema if asked for.
         */
        if (name != NULL) {
                avro_schema_t  schema = iface->schema;
                *name = avro_schema_record_field_name(schema, index);
        }

        return 0;
}
```

The tables I'm working with have more than two columns, so I'm not sure why this error would ever occur? Or is bottled-water trying to access the 2nd field in the primary key index, which only has 1 field? Why would this ever happen?

I am really at a loss as to why this happens, or how to prevent it.

**Comment by samstokes** [comment] 2015-12-04 02:11
I have observed the same error message with the following reproduction steps:

1. Run Bottled Water Docker setup as on README

2. As the test table:
    ```sql
    CREATE TABLE things (id SERIAL PRIMARY KEY, thing INTEGER NOT NULL);
    ```

3. Use `generate_series` to insert a large number of rows in a short period:
    ```sql
    INSERT INTO things (thing) SELECT * FROM generate_series(1, 10000) AS thing;
    ```

About 50% of the time, the BW client crashes during the INSERT.  It's not completely deterministic - others have reproduced it with only 1000 rows, and I've seen it work once for 10000, then fail on a second set of 10000.

Restarting the client works - it comes back up, produces the messages it didn't produce before, and resumes normal operation.  Running the INSERT again will crash it again.

**Comment by samstokes** [comment] 2015-12-04 02:16
(BTW @zcox I have successfully used Bottled Water on tables with more than 2 columns, so I don't think that is the problem per se.  What happens if you use the same table schemas, but insert rows manually in the psql shell rather than writing into them using the firehose?)

**Comment by zcox** [comment] 2015-12-04 02:59
@samstokes [the example app](https://github.com/zcox/data-replication-example) I've been using also provides a simple REST API to insert users & tweets one at a time. That seems to work fine, but I've only used it via curl a few times, I haven't created any large number of users or tweets that way.

I was also able to reproduce the issue using your instructions. I had to run that insert line several times quickly to get BW to crash, but it did indeed crash, with the same error message that I saw with twitter data. I was initially thinking maybe some strange data was coming from the Twitter Streaming API and causing this, but I think our two approaches show this is a bug in Bottled Water. It seems to happen when lots of rows are being inserted into the Postgres table - maybe there's some kind of concurrency problem? I haven't dug into BW source code, not really sure what the problem is.

When I used your instructions I was able to restart BW and keep using it. However with my Twitter data, once BW crashes it never starts properly again. I have to start over with empty users & tweets tables. 

I was pretty bummed to uncover this - I'm using BW as part of an upcoming conference talk. Wanted to show lots of data going from Postgres through Kafka into other data stores, but this is a big blocker.

**Comment by datarace** [comment] 2015-12-08 17:36
I'm getting the same issue doing simple inserts on the example table:

/usr/local/bin/bottledwater: Replication stream was unexpectedly terminated: ERROR:  output_avro_change: row conversion failed: Field index 1 out of range
CONTEXT:  slot "bottledwater", output plugin "bottledwater", in the change callback, associated LSN 0/1768498

**Comment by zcox** [comment] 2015-12-08 18:15
Personally I think Bottled Water is being abandoned and replaced by the [JDBC Connector](http://docs.confluent.io/2.0.0/connect/connect-jdbc/docs/index.html) in Kafka Connect. I haven't tested the JDBC Connector yet, but will be doing so very soon.

**Comment by ewencp** [comment] 2015-12-08 18:26
@zcox It's not being replaced. I'd really like to see Bottled Water converted into a Kafka Connector itself. The JDBC connector is really useful because it's so broad -- pretty much any relational database will have a JDBC driver. However, that generality also comes with limitations; for example, since you cannot get at the underlying change log with all the transactions, you cannot get the full set of info that you could get from Bottled Water. For a lot of applications, that limitation might be acceptable. However, there is still a lot of value in database-specific solutions like Bottled Water. (Other possible tradeoffs include performance, latency, fidelity of data since JDBC may not directly represent all types supported by your database, etc.)

**Comment by zcox** [comment] 2015-12-08 18:46
@ewencp thanks for the reply - I was secretly hoping my comment above would provoke a response from someone at Confluent. :wink: 

Bottled Water is a great concept, for all of the benefits you listed. I hope work does continue on it to get it rock-solid and production-ready, and it would be great to see it integrated with Kafka Connect.

**Comment by ept** [comment] 2015-12-08 19:36
Hello all, I hear you! I'm currently fighting with a few deadlines, but I'm hoping to spend some time on Bottled Water again soon. It definitely deserves to be made production-ready.

**Comment by datarace** [comment] 2015-12-08 20:46
Yes its got great potential I believe

**Comment by bchazalet** [comment] 2015-12-11 16:50
I am having the same issue, and I have been investigating a little.

It seems that the problem is that at some point the `key_index` field, of the schema cache entry that is given back by the lookup, is gone.

In my case, with a simple single-table example, in the cache entry `key_index` the value of `indexrelid` is 24638 and of `inrelid` is 24634. If I keep inserting until it crashes, I see that those values are both 0 just before it stops.

All this happens in `update_frame_with_insert` in `protocol_server.c`: the cache lookup happens, then `extract_tuple_key` is called and from there `tuple_to_avro_key` in `oid2avro.c` is called which will try to make use of the cache's entry `key_index` fields which by now hold plain wrong values. And that's where the error is raised.

Also, I am not sure it's related but I always see the following lines in the postgres debug logs before it fails:
```
DEBUG:  found top level transaction 1454, with catalog changes!
DEBUG:  adding a new snapshot to 1454 at 0/B92175C8
```
I don't know what it means, but it'd be good if someone else can confirm (or infirm) whether it always precedes a crash.

I hope this can help identifying, the problem.

**Comment by msfouad** [comment] 2015-12-13 12:59
I was getting the same issue.

Thanks to @bchazalet changes I'm able to insert table with 33 M rows in PostgreSQL and using bottledwater into kafka without any issue.

**Comment by datarace** [comment] 2015-12-14 09:06
Where are the changes pls - have they been removed ?

Thanks

**Comment by msfouad** [comment] 2015-12-14 09:50
@datarace you can find the changes under @bchazalet  fork 

https://github.com/bchazalet/bottledwater-pg/commit/b427b89f8da8da449081b2f8d0dd6fc77a570e97

until the pull request accepted you can edit the files in your local source and rebuild it.

**Comment by bchazalet** [comment] 2015-12-14 10:48
@msfouad thanks for the feedback, and I'm glad it works for others too.

@datarace to try the changes, and if you're already building from source:
Go to your bottledwater-pg folder, wherever that is
```
cd bottledwater-pg
```
Add the new remote and checkout the right branch:
```
git remote add bchazalet git@github.com:bchazalet/bottledwater-pg.git
git fetch bchazalet
git co --track bchazalet/wip/fixing-issue-32
```
and re-build again following the normal instructions.

**Comment by ept** [comment] 2015-12-14 11:58
I've merged @bchazalet's pull request, which fixes the issue for me. Could others please try it too? Thanks Boris for your help!

**Closed by ept** 2015-12-14 11:58 UTC

**Comment by samstokes** [comment] 2015-12-16 21:52
@ept I confirm that I can no longer reproduce the crash using the `generate_series` approach above on a fresh build from master (commit 63d4d0e).  Thanks @bchazalet !

**Comment by datarace** [comment] 2015-12-17 07:54
works for me - many thanks :)
