### ISSUE TITLE
Numeric datatypes do not appear to work - value lost

### ISSUE THREAD

**Issue by datarace** [confluentinc/bottledwater-pg#38] opened 2016-01-06 14:45 UTC
Postgres type 'numeric' appears to lose value 

Testcase:

1. Create table with numeric column and one row of numeric data

postgres=# create table test (id serial primary key, value numeric);
CREATE TABLE

postgres=# \d+ test
                                             Table "public.test"
 Column |  Type   |                     Modifiers                     | Storage | Stats target | Description
--------+---------+---------------------------------------------------+---------+--------------+-------------
 id     | integer | not null default nextval('test_id_seq'::regclass) | plain   |              |
 value  | numeric |                                                   | main    |              |
Indexes:
    "test_pkey" PRIMARY KEY, btree (id)

postgres=# insert into test (value) values(1.23);
INSERT 0 1

postgres=# select * from test;
 id | value
----+-------
  1 |  1.23
(1 row)

2. Read The data from kafka (note returns 0.0)

./bin/kafka-avro-console-consumer --zookeeper localhost:2181 --from-beginning --topic test  

{"id":{"int":1},"value":{"double":0.0}}

3. Note type is stored as a double in avro schema

# curl -X GET -i -H "Content-Type: application/vnd.schemaregistry.v1+json" \
>     http://localhost:8081/subjects/test-value/versions/1
HTTP/1.1 200 OK
Content-Length: 265
Content-Type: application/vnd.schemaregistry.v1+json
Server: Jetty(8.1.16.v20140903)

{"subject":"test-value","version":1,"id":2,"schema":"{\"type\":\"record\",\"name\":\"test\",\"namespace\":\"com.martinkl.bottledwater.dbschema.public\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"int\"]},{\"name\":\"value\",\"type\":[\"null\",\"double\"]}]}"}

**Comment by ept** [comment] 2016-01-10 18:20
Yes, I unfortunately didn't have time yet to add support for numeric. Pull requests welcome! Closing this issue as duplicate of #4.

**Closed by ept** 2016-01-10 18:20 UTC
